let
    // Substitua a primeira linha com a tabela e a coluna da data
    colDataFonte = #"Dados dos pedidos"[Data do pedido],

    menorData = Date.StartOfYear(List.Min(colDataFonte)),
    maiorData = Date.EndOfYear(List.Max(colDataFonte)),
    qtdDias = Duration.TotalDays( maiorData - menorData ) + 1,
    #"Lista Criada" = List.Dates(menorData, qtdDias, #duration(1, 0, 0, 0)),
    #"Tabela Criada" = Table.FromList(#"Lista Criada", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tabela Criada",{{"Column1", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "data"}}),
    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([data]), Int64.Type),
    #"Trimestre Inserido" = Table.AddColumn(#"Mês Inserido", "Trimestre", each Date.QuarterOfYear([data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Trimestre Inserido", "Nome do Mês", each Date.MonthName([data]), type text)
in
    #"Nome do Mês Inserido"
